const SET_USER='SET_USER';
const TAG_LIST='TAG_LIST';
const ARTICLE_LIST='ARTICLE_LIST'
const ARTICLE='ARTICLE'
const UPDATE_ARTICLE='UPDATE_ARTICLE'
const COMMENTS='COMMENTS'
export {SET_USER,TAG_LIST,ARTICLE_LIST,ARTICLE,UPDATE_ARTICLE,COMMENTS}